version: '3'
services:
  front-end:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
        - /app/node_modules
        - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true